# Generated by Django 4.2.2 on 2023-07-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postmind', '0002_postcard_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='is_approved',
        ),
        migrations.CreateModel(
            name='PendingPostCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postmind.postcard')),
            ],
        ),
    ]
