# Generated by Django 4.2.2 on 2023-07-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmind', '0003_remove_postcard_is_approved_pendingpostcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcard',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PendingPostCard',
        ),
    ]
