# Generated by Django 4.2.2 on 2023-07-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postmind', '0004_postcard_is_approved_delete_pendingpostcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='postcard',
            name='content',
            field=models.TextField(max_length=300),
        ),
    ]
